/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique.modifications;

import base.activerecord.Link;
import base.activerecord.Word;
import javax.swing.JOptionPane;
import main.donnees.ListLanguages;

/**
 *
 * @author Maxime
 */
public class PanAjoutOptimise extends javax.swing.JPanel {

    /**
     * Creates new form PanAjoutOptimise
     */
    public PanAjoutOptimise() {
        initComponents();
        initLanguages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabTitre = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        choixLangue1 = new javax.swing.JComboBox();
        confirmLangues = new javax.swing.JLabel();
        boutonValider = new javax.swing.JButton();
        choixLangue2 = new javax.swing.JComboBox();

        setPreferredSize(new java.awt.Dimension(600, 450));

        LabTitre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LabTitre.setForeground(new java.awt.Color(0, 102, 0));
        LabTitre.setText("Ajout de données : ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Caractéristiques", "Valeur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        choixLangue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixLangue1ActionPerformed(evt);
            }
        });

        boutonValider.setText("Valider l'ajout");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderActionPerformed(evt);
            }
        });

        choixLangue2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Français", "Anglais", "Allemand", "Chinois" }));
        choixLangue2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixLangue2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(boutonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(choixLangue1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(choixLangue2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmLangues, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LabTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(confirmLangues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(choixLangue2)
                        .addComponent(choixLangue1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(boutonValider)
                .addContainerGap(182, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderActionPerformed
        // TODO add your handling code here:

        // Validate all data
        System.out.println("Language 1 : " + this.language1 + " ; Language 2 : " + this.language2);
        // Add word 1
        Word word1 = new Word(this.language1, jTable1.getModel().getValueAt(0, 1).toString(), jTable1.getModel().getValueAt(1, 1).toString(), jTable1.getModel().getValueAt(2, 1).toString());
        word1.insert(false);
        // Add word 2
        Word word2 = new Word(this.language2, jTable1.getModel().getValueAt(3, 1).toString(), jTable1.getModel().getValueAt(4, 1).toString(), jTable1.getModel().getValueAt(5, 1).toString());
        word2.insert(false);
        // Add liaison
        Link link = new Link(language1 + language2, word1.getNom(), word2.getNom());
        link.insert(false);

        // Finish
        JOptionPane.showMessageDialog(null, "Insert with success !", "Insert data", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_boutonValiderActionPerformed

    private void choixLangue1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixLangue1ActionPerformed
        // TODO add your handling code here:

        // Get item
        this.language1 = getLanguageWithIndice(choixLangue1.getSelectedIndex());
        jTable1.setValueAt("Mot " + choixLangue1.getSelectedItem(), 0, 0);
        jTable1.setValueAt("Phonétique " + choixLangue1.getSelectedItem(), 1, 0);
        jTable1.setValueAt("Genre " + choixLangue1.getSelectedItem(), 2, 0);
    }//GEN-LAST:event_choixLangue1ActionPerformed

    private void choixLangue2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixLangue2ActionPerformed
        // TODO add your handling code here:

        // Get item
        this.language2 = getLanguageWithIndice(choixLangue2.getSelectedIndex());
        jTable1.setValueAt("Mot " + choixLangue2.getSelectedItem(), 3, 0);
        jTable1.setValueAt("Phonétique " + choixLangue2.getSelectedItem(), 4, 0);
        jTable1.setValueAt("Genre " + choixLangue2.getSelectedItem(), 5, 0);
    }//GEN-LAST:event_choixLangue2ActionPerformed

    public String getLanguageWithIndice(int indice) {
        /*switch (indice) {
            case 0:
                return "fr";
            case 1:
                return "en";
            case 2:
                return "de";
            case 3:
                return "ch";
        }
        return "";*/
        return ListLanguages.listLanguages.get(indice).getAbbr();
    }

    /**
     * First word's language.
     */
    private String language1 = "";

    /**
     * Second word's language.
     */
    private String language2 = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabTitre;
    private javax.swing.JButton boutonValider;
    private javax.swing.JComboBox choixLangue1;
    private javax.swing.JComboBox choixLangue2;
    private javax.swing.JLabel confirmLangues;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void initLanguages() {
        // Create Array With Languages
        String[] array = new String[ListLanguages.listLanguages.size()];
        for(int i=0;i<array.length;i++) {
            array[i] = ListLanguages.listLanguages.get(i).getName();
        }
        // Set Models
        choixLangue1.setModel(new javax.swing.DefaultComboBoxModel(array));
        choixLangue2.setModel(new javax.swing.DefaultComboBoxModel(array));
    }
}
