/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique.modifications;

import base.ModifPressPap;
import base.activerecord.Mot;
import javax.swing.JOptionPane;
import main.donnees.Donnees;

/**
 *
 * @author Maxime
 */
public class PanAjoutMots extends javax.swing.JPanel {

    /**
     * Creates new form PanAjoutMots
     */
    public PanAjoutMots() {
        initComponents();

        /* Activer le contraste */
        activerContraste();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        confirmChoix = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        saisieNom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        saisiePhonetique = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        saisieGenre = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        collerNom = new javax.swing.JButton();
        collerGenre = new javax.swing.JButton();
        collerPhonetique = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 0));
        jLabel5.setText("Ajout de mots : ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Français", "Allemand", "Anglais", "Chinois" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom");

        jLabel2.setText("Phonétique");

        jLabel3.setText("Genre");

        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        collerNom.setText("Coller");
        collerNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collerNomActionPerformed(evt);
            }
        });

        collerGenre.setText("Coller");
        collerGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collerGenreActionPerformed(evt);
            }
        });

        collerPhonetique.setText("Coller");
        collerPhonetique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collerPhonetiqueActionPerformed(evt);
            }
        });

        jButton1.setText("vider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(confirmChoix, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(212, 212, 212)
                                .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saisieGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(collerGenre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saisiePhonetique, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(collerPhonetique))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saisieNom, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(collerNom)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox1)
                    .addComponent(confirmChoix, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saisieNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(collerNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saisiePhonetique, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(collerPhonetique, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saisieGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(collerGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(ajouter)
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:

        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                type = "fr";
                break;
            case 1:
                type = "de";
                break;
            case 2:
                type = "en";
                break;
            case 3:
                type = "ch";
                break;
        }

        confirmChoix.setText(type + ":OK");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void collerNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collerNomActionPerformed
        // TODO add your handling code here:

        /* Press papier */
        ModifPressPap mpp = new ModifPressPap();
        saisieNom.setText(mpp.getClipboardContents());
    }//GEN-LAST:event_collerNomActionPerformed

    private void collerPhonetiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collerPhonetiqueActionPerformed
        // TODO add your handling code here:

        /* Press papier */
        ModifPressPap mpp = new ModifPressPap();
        saisiePhonetique.setText(mpp.getClipboardContents());
    }//GEN-LAST:event_collerPhonetiqueActionPerformed

    private void collerGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collerGenreActionPerformed
        // TODO add your handling code here:

        /* Press papier */
        ModifPressPap mpp = new ModifPressPap();
        saisieGenre.setText(mpp.getClipboardContents());
    }//GEN-LAST:event_collerGenreActionPerformed

    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        // TODO add your handling code here:

        /* Création du mot */
        if (saisieNom.getText().equals("") || saisieGenre.getText().equals("") || saisiePhonetique.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Erreur: champs vides.", "Information", JOptionPane.ERROR_MESSAGE);
        } else {
            Mot mot = new Mot(type, saisieNom.getText(), saisiePhonetique.getText(), saisieGenre.getText());
            if (mot.insert(false)) {
                JOptionPane.showMessageDialog(null, "Mot ajouté avec succès.", "Succès", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Erreur lors de l'insertion.", "Information", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_ajouterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        // remise à 0
        saisieGenre.setText("");
        saisieNom.setText("");
        saisiePhonetique.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    public String type = "fr";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton collerGenre;
    private javax.swing.JButton collerNom;
    private javax.swing.JButton collerPhonetique;
    private javax.swing.JLabel confirmChoix;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField saisieGenre;
    private javax.swing.JTextField saisieNom;
    private javax.swing.JTextField saisiePhonetique;
    // End of variables declaration//GEN-END:variables

    public final void activerContraste() {
        /* Modification PANEL */
        this.setBackground(Donnees.contraste.couleurs.get("fond"));

        /* LABEL TITRE */
        jLabel5.setForeground(Donnees.contraste.couleurs.get("labelTitre"));
        jLabel5.setBackground(Donnees.contraste.couleurs.get("fond"));

        /* LABEL */
        jLabel1.setBackground(Donnees.contraste.couleurs.get("fond"));
        jLabel1.setForeground(Donnees.contraste.couleurs.get("label"));
        jLabel2.setBackground(Donnees.contraste.couleurs.get("fond"));
        jLabel2.setForeground(Donnees.contraste.couleurs.get("label"));
        jLabel3.setBackground(Donnees.contraste.couleurs.get("fond"));
        jLabel3.setForeground(Donnees.contraste.couleurs.get("label"));
        confirmChoix.setBackground(Donnees.contraste.couleurs.get("fond"));
        confirmChoix.setForeground(Donnees.contraste.couleurs.get("label"));

        /* TEXT FIELD */
        saisieNom.setForeground(Donnees.contraste.couleurs.get("textField"));
        saisieNom.setBackground(Donnees.contraste.couleurs.get("textFieldFond"));
        saisieGenre.setForeground(Donnees.contraste.couleurs.get("textField"));
        saisieGenre.setBackground(Donnees.contraste.couleurs.get("textFieldFond"));
        saisiePhonetique.setForeground(Donnees.contraste.couleurs.get("textField"));
        saisiePhonetique.setBackground(Donnees.contraste.couleurs.get("textFieldFond"));

        /* BOUTONS */
        jButton1.setForeground(Donnees.contraste.couleurs.get("bouton"));
        jButton1.setBackground(Donnees.contraste.couleurs.get("boutonFond"));
        collerPhonetique.setForeground(Donnees.contraste.couleurs.get("bouton"));
        collerPhonetique.setBackground(Donnees.contraste.couleurs.get("boutonFond"));
        collerNom.setForeground(Donnees.contraste.couleurs.get("bouton"));
        collerNom.setBackground(Donnees.contraste.couleurs.get("boutonFond"));
        collerGenre.setForeground(Donnees.contraste.couleurs.get("bouton"));
        collerGenre.setBackground(Donnees.contraste.couleurs.get("boutonFond"));
        ajouter.setForeground(Donnees.contraste.couleurs.get("bouton"));
        ajouter.setBackground(Donnees.contraste.couleurs.get("boutonFond"));

    }
}
