/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique.options;

import static graphique.chercher.PanChercher.applicationCouleur;
import java.util.ArrayList;
import javax.swing.JComponent;

/**
 *
 * @author Maxime
 */
public class PanContraste extends javax.swing.JPanel {

    /**
     * Creates new form PanContraste
     */
    public PanContraste() {
        initComponents();
        
        // Activation du contraste
        activationContraste();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion des contrastes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    /**
     * Méthode qui active le contraste de ce panel.
     */
    public final void activationContraste() {
        // Liste qui va servir pour tous les composants
        ArrayList<JComponent> liste;
        
        // Pour la couleur de fond général
        liste = new ArrayList<>();
        liste.add(this);
        liste.add(jLabel1);
        applicationCouleur("fond", liste, true);
        
        // Pour la couleur des labels titre
        liste = new ArrayList<>();
        liste.add(jLabel1);
        applicationCouleur("labelTitre", liste, false);
    }
}
