/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique.options;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import main.donnees.Donnees;
import main.donnees.Options;

/**
 *
 * @author blaiseWin
 */
public class PanOptions extends javax.swing.JPanel {

    /**
     * Creates new form PanOptions
     */
    public PanOptions() {
        initComponents();

        // Initialisation données
        initialiserDonneesPanel();

        // Activation du contraste
        activerContraste();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        checkVerbeux = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        checkVoice = new javax.swing.JCheckBox();
        boutonSauve = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        choixDossier = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(600, 450));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Options sur le logiciel : ");

        jLabel2.setText("Activer le mode verbeux : ");

        jLabel3.setText("Activer les voix : ");

        boutonSauve.setText("Sauvegarder");
        boutonSauve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSauveActionPerformed(evt);
            }
        });

        jLabel4.setText("Choisir le dossier qui contient les voix : ");

        choixDossier.setText("Choisir");
        choixDossier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixDossierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(boutonSauve, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(choixDossier))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(checkVoice)
                                .addComponent(checkVerbeux, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkVerbeux))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkVoice)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choixDossier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(boutonSauve)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boutonSauveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSauveActionPerformed
        // TODO add your handling code here:

        // Sauvegarde des données
        sauvegarderDonnees();
    }//GEN-LAST:event_boutonSauveActionPerformed

    private void choixDossierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixDossierActionPerformed
        // TODO add your handling code here:

        JFileChooser jfc = new JFileChooser();
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        String monFichier;
        String approve = "Choisir";
        int resultatEnregistrer = jfc.showDialog(jfc, approve);
        if (resultatEnregistrer == JFileChooser.APPROVE_OPTION) {

            // Dossier
            Options.addValue("dossier", jfc.getSelectedFile().toString());

        }
    }//GEN-LAST:event_choixDossierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonSauve;
    private javax.swing.JCheckBox checkVerbeux;
    private javax.swing.JCheckBox checkVoice;
    private javax.swing.JButton choixDossier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    /**
     * Activation du contraste
     */
    public final void activerContraste() {
        /* Modification PANEL */
        this.setBackground(Donnees.contraste.couleurs.get("fond"));

        // Label titre
        jLabel1.setBackground(Donnees.contraste.couleurs.get("fond"));
        jLabel1.setForeground(Donnees.contraste.couleurs.get("labelTitre"));

        // Labels
        jLabel2.setBackground(Donnees.contraste.couleurs.get("fond"));
        jLabel2.setForeground(Donnees.contraste.couleurs.get("label"));
        jLabel3.setBackground(Donnees.contraste.couleurs.get("fond"));
        jLabel3.setForeground(Donnees.contraste.couleurs.get("label"));
        jLabel4.setBackground(Donnees.contraste.couleurs.get("fond"));
        jLabel4.setForeground(Donnees.contraste.couleurs.get("label"));

        // Modification bouton
        boutonSauve.setBackground(Donnees.contraste.couleurs.get("boutonFond"));
        boutonSauve.setForeground(Donnees.contraste.couleurs.get("bouton"));
        choixDossier.setBackground(Donnees.contraste.couleurs.get("boutonFond"));
        choixDossier.setForeground(Donnees.contraste.couleurs.get("bouton"));
    }

    /**
     * Initialisation des données du panel
     */
    private void initialiserDonneesPanel() {
        // Les CheckBox
        checkVerbeux.setSelected(Donnees.isModeVerbeux());
        checkVoice.setSelected(Donnees.isVoice());
    }

    private void sauvegarderDonnees() {
        // Les CheckBox
        String modeVerbeux = (checkVerbeux.isSelected()) ? "oui" : "non";
        Options.addValue("modeverbeux", modeVerbeux);
        String voice = (checkVoice.isSelected()) ? "oui" : "non";
        Options.addValue("voice", voice);

        // Sauvegarde

    }
}
