/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graphique;

import java.awt.Color;

/**
 *
 * @author Maxime
 */
public class ValeursDefauts extends javax.swing.JPanel {

    /**
     * Creates new form ValeursDefauts
     */
    public ValeursDefauts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        jButton1.setText("jButton1");

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Méthode principale
    public static void main(String[] args) {
        ValeursDefauts defaut = new ValeursDefauts();
        
        Color c = defaut.getBackground();
        afficherCouleur("Couleur de fond du panel", c);
        
        c = defaut.jButton1.getForeground();
        afficherCouleur("Couleur du bouton", c);
        
        c = defaut.jButton1.getBackground();
        afficherCouleur("Couleur de fond du bouton", c);
        
        c = defaut.jTextField1.getForeground();
        afficherCouleur("Couleur du TextField", c);
        
        c = defaut.jTextField1.getBackground();
        afficherCouleur("Couleur de fond du TextField", c);
    }

    public static void afficherCouleur(String message, Color c) {
        System.out.println(message+" : {"+c.getRed()+";"+c.getGreen()+";"+c.getBlue()+"}");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
